<?php

/**
 * Implementation of hook_perm()
 */
function hosting_piwik_perm() {
  return array('administer piwik');
}

/**
 * Implementation of hook_menu()
 */
function hosting_piwik_menu() {

  $items = array();
  
  $items['admin/hosting/piwik'] = array(
    'title' => t('Piwik'),
    'access arguments' => array('administer piwik'),
    'file' => 'hosting_piwik.admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hosting_piwik_settings'),    
  );

  return $items;
}


/**
 * Implementation of hook_insert()
 */
function hosting_piwik_insert($node) {
  db_query("INSERT INTO {hosting_piwik_piwik}
             (vid, nid, access_token)
             VALUES (%d, %d, '%s')", $node->vid, $node->nid, $node->monitoring_access_token);
}

/**
 * Implementation of hook_update()
 */
function hosting_piwik_update($node) {
  //add if needed
}

/**
 * Implementation of hook_delete()
 */
function hosting_piwik_delete($node) {
  db_query("DELETE FROM {hosting_piwik_piwik}
            WHERE nid=%d", $node->nid);
}

/**
 * Implementation of hook_delete_revision()
 */
function hosting_piwik_delete_revision($node) {
  db_query("DELETE FROM {hosting_piwik_piwik}
            WHERE vid=%d", $node->vid);
}

function hosting_piwik_load($node) {
  $site_aliases = array();
  $resource = db_query("SELECT alias
                        FROM {hosting_site_alias}
                        WHERE nid=%d", $node->nid);
  while ($row = db_result($resource)) {
    $site_aliases[] = $row;
  }

  $additions['monitoring_access_token'] = db_result(
      db_query("SELECT access_token
                FROM {hosting_piwik_piwik}
                WHERE nid=%d", $node->nid)
  );
  $additions['site_aliases'] = $site_aliases;

  module_load_include('inc', 'hosting_piwik',
                      'hosting_piwik.db');
  $additions['piwik_site_id'] = hosting_piwik_get_piwik_id($node->nid);

  return $additions;
}

/**
 * Implementation of hook_nodeapi()
 */
function hosting_piwik_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($node->type == 'site') {
    switch ($op) {
      case 'insert':
        hosting_piwik_insert($node);
        break;
      case 'update':
        hosting_piwik_update($node);
        break;
      case 'delete' :
        hosting_piwik_delete($node);
        break;
      case 'delete revision':
        hosting_piwik_delete_revision($node);
        break;
      case 'load':
        return hosting_piwik_load($node);
        break;
    }
  }
}

